### ISSUE TITLE
Cannot reproduce EnergyPlusModel with codegen script

### ISSUE THREAD

**Issue by KevinLurtis** [taoning/epmodel#5]
Hello, thank you in advance for your time. Hopefully you can help us . 

We're trying to use the code generation script to create an extended `EnergyPlusModel` that contains additional definitions that we need to use.

So far, we've managed to run the `codegen.py` script, but have not been able to reproduce the `EnergyPlusModel` provided by the package in `src/epmodel/epmodel.py`, so we don't have a "baseline" from which to generate additional definitions.

# System Configuration.

- OS: `Linux 6.9.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 x86_64 GNU/Linux`
- Python version: `3.10.11`.
- `epmodel` repository version: `main`: `c4496af4223bd73aeb028e867248c20b4bc5e612`.
- Python environment libraries, from an install of `datamodel-code-generator`:

```
> pip freeze
annotated-types==0.7.0
argcomplete==3.3.0
black==24.4.2
click==8.1.7
datamodel-code-generator==0.25.6
dnspython==2.6.1
email_validator==2.1.1
genson==1.3.0
idna==3.7
inflect==5.6.2
isort==5.13.2
Jinja2==3.1.4
MarkupSafe==2.1.5
mypy-extensions==1.0.0
packaging==24.0
pathspec==0.12.1
platformdirs==4.2.2
pydantic==2.7.3
pydantic_core==2.18.4
PyYAML==6.0.1
toml==0.10.2
tomli==2.0.1
typing_extensions==4.12.1
```

# Details.
We've followed the steps described in the `README.md`, and run `python codegen.py`. We have encountered and fixed the following issues, which have gotten us to a working script, and closer to what `epmodel.py` contains:

1. The script could not be run because of a mis-named keys file. Updated: `keys2.txt -> keys.txt`.
2. The model generated produces obsolete `con*` functions from the `pydantic` library. Changed:

```
generate(
    ...,
    field_constraints=True,
    use_annotated=True,
    ...,)
```

So far, we've noticed the following differences with the model in `epmodel.py`:

1.`epmodel.py`: Default values may be defined as `= value`. Ours: Default values may be defined as `Field(value, ...)`. Apparently the value is the same, though I haven't checked all instances of this.
2. Our `Enum` classes have a `field_ = ""` field, where `epmodel.py` doesn't. 
3. Our model does not have an `EPBoolean`, and instead uses:

```
class DoZoneSizingCalculation(Enum):
    field_ = ""
    no = "No"
    yes = "Yes"
```

4. Some definitions are not created, such as `Extension` and `MaterialPropertyGlazingSpectralData`.
5. Different names. For example `epmodel.py`: `CeilingHeightEnum`, where ours: `CeilingHeight`.

I have observed that in the commit history:
1. The commit `c1493aa88306d378257165cacc3de579d706d29b` uses a different version of python to seemingly generate additional keys.
2.  The commit `971972f4ab238eea65d5da0e003c31d9a639a6f6` renames `DoZoneSizingCalculation` to `EPBoolean`, and also removes enum empty fields defined as `field_ = ""`.

From what I have seen, it seems that `epmodel.py` may have been generated:
1. With a different `keys.txt` file.
4. With different `generate` settings.
5. With different `datamodel-code-generator`.
6. With manual renaming of `DoZoneSizingCalculation` to `EPBoolean`.

More generally, there seems to be missing steps and/or data, so the `epmodel.py` cannot be reproduced.

What would be missing from the process of creating `epmodel.py`? It's quite a maintenance burden to have to manually extend the generated model, and I'm not entirely sure if there are any differences with EnergyPlus' epJSON schema.

---
I hope this is helpful!
Thank you for your time.

**Comment by taoning** [comment]
You found all the quirks!   Yes, indeed those are all manual changes as far as I can remember.  I will have revisit what I did and come back with better docs. 

In the meantime, we also wanted to expand the keys to include more objects. What are the ones you want to include? We realize we missed quite a few relatively common ones.

**Comment by taoning** [comment]
Just updated with the new objects.
Most of the previous manual process is now automated, except for the "protected_namespace" warning, which i had to manually override.
